# Render Deployment Configuration
# 
# This file configures the deployment settings for the Account Ledger Software
# backend on Render.com platform.
# 
# Features:
# - Automatic deployment from GitHub
# - Environment variable management
# - Health check configuration
# - Build and runtime settings
# 
# @author Account Ledger Team
# @version 1.0.0

services:
  - type: web
    name: account-ledger-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start-with-keepalive
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://property-flow-design.vercel.app
      - key: BCRYPT_SALT_ROUNDS
        value: 10000
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100 